# GitAction åç§°
name: docs PR check

# æ­¤CI/CDè§¦å‘æ—¶çš„äº‹ä»¶ push:åœ¨ä»£ç æäº¤æ—¶è‡ªåŠ¨è§¦å‘
on:
  pull_request:
    branches:
      - master

# ä¸€ä¸ª CI/CD çš„å·¥ä½œæµæœ‰è®¸å¤š jobs ç»„æˆï¼Œæ¯”å¦‚æœ€å…¸å‹çš„ job æ˜¯ lintï¼Œtestï¼Œbuildç­‰ï¼Œè¿™é‡Œèµ·å build-and-deploy
jobs:
  check-pr-build:
    runs-on: ubuntu-latest # è¿è¡Œworkflowçš„æœåŠ¡å™¨ç³»ç»Ÿï¼šubuntuæœ€æ–°ç‰ˆæœ¬

    steps:
      - name: checkout ğŸ”
        uses: actions/checkout@v2

      - name: Set node version to 16 ğŸ› ï¸
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install deps ğŸ“¦
        run: yarn install

      - name: Build ğŸ› ï¸
        run: yarn run docs:build
